CREATE DATABASE WMS
GO
 
 USE wms
 GO 
-- Tabela: DIM_USUARIO
CREATE TABLE DimUsuario (
    EMAIL NVARCHAR(255) PRIMARY KEY,
    NOME NVARCHAR(255) NOT NULL,
    SENHA NVARCHAR(255) NOT NULL,
    DATANASC DATE,
    DATAENTRADA DATE
);

-- Tabela: FACT_ADICIONAR
CREATE TABLE FactAdicionar (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    EMAIL NVARCHAR(255) NOT NULL,
    SN BIGINT NOT NULL
);

-- Tabela: DIM_PROFESSOR
CREATE TABLE DimProfessor (
    SN BIGINT PRIMARY KEY,
    NOME NVARCHAR(255) NOT NULL,
    SENHA NVARCHAR(255) NOT NULL
);

-- Tabela: FACT_PROFESSOR_PRODUTO
CREATE TABLE FactProfessorProduto (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    SN BIGINT NOT NULL,
    CODIGO BIGINT NOT NULL
);

-- Tabela: FACT_USUARIO_PRODUTO
CREATE TABLE FactUsuarioProduto (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    EMAIL NVARCHAR(255) NOT NULL,
    CODIGO BIGINT NOT NULL
);

-- Tabela: DIM_PRODUTO
CREATE TABLE DimProduto (
    CODIGO BIGINT PRIMARY KEY,
    NOME_BASICO NVARCHAR(255) NOT NULL,
    NOME_MODIFICADOR NVARCHAR(255),
    DESCRICAO_TECNICA NVARCHAR(MAX),
    PRECO_DE_AQUISICAO DECIMAL(10, 2),
    FABRICANTE NVARCHAR(255),
    FORNECEDOR NVARCHAR(255),
    ENDERECAMENTO NVARCHAR(255),
    VALIDADE DATE,
    OBSERVACOES_ADICIONAL NVARCHAR(MAX),
    IMAGEM VARBINARY(MAX),
    UNIDADE NVARCHAR(50),
    PRECO_DE_VENDA DECIMAL(10, 2),
    FRAGILIDADE BIT
);

-- Tabela: FACT_CATEGORIA
CREATE TABLE FactCategoria (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    CODIGO BIGINT NOT NULL,
    ID_CATEGORIA BIGINT NOT NULL
);

CREATE TABLE DimCategoria (
    ID_CATEGORIA BIGINT PRIMARY KEY IDENTITY(1,1),
    CATEGORIA NVARCHAR(255) NOT NULL
);

-- Tabela: RECEBIMENTO
CREATE TABLE FactRecebimento (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    DATA_RECEB DATE NOT NULL,
    QUANT INT NOT NULL,
    CODIGO BIGINT NOT NULL
);

go 

ALTER TABLE FactAdicionar
ADD CONSTRAINT FK_Adicionar_Usuario FOREIGN KEY (SN)
REFERENCES DimProfessor(SN);
go 

ALTER TABLE FactAdicionar
ADD CONSTRAINT FK2_Adicionar_Usuario FOREIGN KEY (EMAIL)
REFERENCES DimUsuario(EMAIL);
go 
--professor e prod
ALTER TABLE FactProfessorProduto
ADD CONSTRAINT FK_Professor_Produto FOREIGN KEY (SN)
REFERENCES DimProfessor(SN);
go 
ALTER TABLE FactProfessorProduto
ADD CONSTRAINT FK2_Professor_Produto FOREIGN KEY (CODIGO)
REFERENCES DimProduto(CODIGO);
go 

--Usuario e prod
ALTER TABLE FactUsuarioProduto
ADD CONSTRAINT FK_Usuario_Produto FOREIGN KEY (EMAIL)
REFERENCES  DimUsuario(EMAIL);
go 
ALTER TABLE FactUsuarioProduto
ADD CONSTRAINT FK2_Usuario_Produto  FOREIGN KEY (CODIGO)
REFERENCES DimProduto(CODIGO);
go 
-----PRODUTO E SUA CATEGORIA



ALTER TABLE FactCategoria
ADD CONSTRAINT FK_Categoria_Produto  FOREIGN KEY (CODIGO)
REFERENCES DimProduto(CODIGO);
go 
ALTER TABLE FactCategoria
ADD CONSTRAINT FK2_Categoria_Produto  FOREIGN KEY (ID_CATEGORIA)
REFERENCES DimCategoria(ID_CATEGORIA);
go

--Recebimento de prod

ALTER TABLE FactRecebimento
ADD CONSTRAINT FK_Recebimento_Produto  FOREIGN KEY (CODIGO)
REFERENCES DimProduto(CODIGO);